CLASS zbp_i_ders_ar03_cust DEFINITION
  PUBLIC
  ABSTRACT
  FINAL
  FOR BEHAVIOR OF zi_ders_ar03_cust.
  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.

CLASS zbp_i_ders_ar03_cust IMPLEMENTATION.
ENDCLASS.
