CLASS zbp_i_ders_ar03_v2 DEFINITION
  PUBLIC
  ABSTRACT
  FINAL
  FOR BEHAVIOR OF zi_ders_ar03_v2.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.

CLASS zbp_i_ders_ar03_v2 IMPLEMENTATION.
ENDCLASS.
